### PR TITLE
Create an On-Boarding guide

### PR DESCRIPTION
**Pull request by ahdezma**
- This guide include API development with Apio Architect from scratch
- Available in both Groovy and Kotlin Gradle DSL
- Available in both Java and Kotlin
- Complete examples
- Runnable with a `bndrun`

### CODE REVIEW

**Comment by dgomezg** [comment]
Using Groovy & Kotlin seems a bit misleading for me. While showing that somethings can be done with Kotlin in Liferay could be an interesting idea, but I'd rather replace Groovy by Java as, in fact, the Groovy option is not showing groovy code but plain java code.

**Comment by dgomezg** [comment]
Added some suggestions.

I've followed the onboarding tutorial and created my first API with no problems (except I had to use Java 8 instead of java 11). Should we add that at the description of the onboarding?

LGTM

**Comment by nhpatt** [comment]
The only change to support Java 11 should be the -runee: JavaSE-1.8 in the bnd.run, right?

**Comment by dgomezg** [comment]
> The only change to support Java 11 should be the -runee: JavaSE-1.8 in the bnd.run, right?

I've  tried both under Java 11:

`sdk use java 11.0.1-open`

with `-runee: JavaSE-1.8`

``` 
> Task :resolve FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=apio.architect.example)
          ⇒ [apio.architect.example version=1.0.0]
              ⇒ osgi.ee: (&(osgi.ee=JavaSE)(version=11))
...
```

with `-runee: JavaSE-1.11`

```
> Task :resolve FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.apache.aries.jax.rs.whiteboard)
          ⇒ [org.apache.aries.jax.rs.whiteboard version=1.0.1]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=javax.ws.rs.client))
                  ⇒ [org.apache.aries.javax.jax.rs-api version=1.0.1]
                      ⇒ osgi.ee: (&(osgi.ee=JavaSE)(version=1.8))
```  

I will dig into those dependency problems later.

**Comment by ahdezma** [comment]
I just try the whole On-Boarding with Java 11 and I extract a couple conclusions:

- You need to use Gradle 5.0 to use Java 11. Just change `gradle/wrapper/gradle-wrapper.properties` to:

```properties
#Thu Dec 20 11:31:08 CET 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-all.zip
```

- In BndRun, the `-runee` value for Java 11 is `JavaSE-11`, not `JavaSE-1.11`
- When you change that, resolution fails for some of the JAX-RS Whiteboard bundles, because they don't support Java 11 yet. CXF is already working on it

**Comment by nhpatt** [comment]
LGTM, merging :)

**Pull request merged**
